# Generated by Django 5.0.4 on 2024-04-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_dados_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_medico',
            old_name='Especialidade',
            new_name='especialidade',
        ),
        migrations.RemoveField(
            model_name='dados_medico',
            name='foto_de_oerfil',
        ),
        migrations.AddField(
            model_name='dados_medico',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='foto_perfil'),
        ),
    ]
